name: Upload

on:
  workflow_dispatch
  push:
    branches:
      - main
    paths:
      - 'cfn-tlspk-cluster-bootstrapper.yaml'
      - 'tlspk-helper.sh'
      - 'tlspk-helper.README.txt'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload Files
      run: |
        aws s3 cp cfn-tlspk-cluster-bootstrapper.yaml s3://venafi-ecosystem/tlspk/
        aws s3 cp tlspk-helper.sh                     s3://venafi-ecosystem/tlspk/
        aws s3 cp tlspk-helper.README.txt             s3://venafi-ecosystem/tlspk/
